dependencies:
  - python=3
  - pip:
    - spacy
    - ipykernel
    - scipy
    - numpy
    - scikit-learn
    - matplotlib
    - pandas
    - thinc
    - Seaborn
    - Statsmodels
    - PyMC
    - Shogun
    - Gensim
    - Orange
    - PyMVPA
    - Theano
    - PyLearn
    - Decaf
    - Nolearn
    - OverFeat
    - Hebel
    - Neurolab
    
