dependencies:
  - python=3
  - pip:
    - spacy
    - ipykernel
    - scipy
    - numpy
    - scikit-learn
    - matplotlib
    - pandas
    - thinc
    - alabaster
    - altgraph
    - anaconda-client
    - anaconda-navigator
    - anaconda-project
    - argon2-cffi
    - asn1crypto
    - astroid
    - astropy
    - async-generator
    - atomicwrites
    - attrs
    - autopep8
    - Babel
    - backcall
    - backports.functools-lru-cache
    - backports.shutil-get-terminal-size
    - backports.tempfile
    - backports.weakref
    - bcrypt
    - beautifulsoup4
    - bitarray
    - bkcharts
    - bleach
    - bokeh
    - boto
    - Bottleneck
    - brotlipy
    - certifi
    - cffi
    - chardet
    - click
    - cloudpickle
    - clyent
    - colorama
    - comtypes
    - conda
    - conda-build
    - conda-package-handling
    - conda-verify
    - contextlib2
    - cryptography
    - cycler
    - Cython
    - cytoolz
    - dask
    - decorator
    - defusedxml
    - diff-match-patch
    - dill
    - distributed
    - docutils
    - entrypoints
    - et-xmlfile
    - fast-histogram
    - fastcache
    - filelock
    - flake8
    - Flask
    - fsspec
    - future
    - gevent
    - glob2
    - glue-core
    - glue-vispy-viewers
    - glueviz
    - greenlet
    - h5py
    - HeapDict
    - html5lib
    - idna
    - imageio
    - imagesize
    - importlib-metadata
    - iniconfig
    - intervaltree
    - ipykernel
    - ipython
    - ipython-genutils
    - ipywidgets
    - isort
    - itsdangerous
    - jdcal
    - jedi
    - Jinja2
    - joblib
    - json5
    - jsonschema
    - jupyter
    - jupyter-client
    - jupyter-console
    - jupyter-core
    - jupyterlab
    - jupyterlab-pygments
    - jupyterlab-server
    - keyring
    - kiwisolver
    - lazy-object-proxy
    - libarchive-c
    - llvmlite
    - locket
    - lxml
    - MarkupSafe
    - matplotlib
    - mccabe
    - menuinst
    - mistune
    - mkl-fft
    - mkl-random
    - mkl-service
    - mock
    - more-itertools
    - mpl-scatter-density
    - mpmath
    - msgpack
    - multipledispatch
    - myTranslator
    - navigator-updater
    - nbclient
    - nbconvert
    - nbformat
    - nest-asyncio
    - networkx
    - nltk
    - nose
    - notebook
    - numba
    - numexpr
    - numpy
    - numpydoc
    - olefile
    - openpyxl
    - packaging
    - pandas
    - pandocfilters
    - paramiko
    - parso
    - partd
    - path
    - pathlib2
    - pathtools
    - patsy
    - pefile
    - pep8
    - pexpect
    - pickleshare
    - Pillow
    - pip
    - pkginfo
    - plotly
    - pluggy
    - ply
    - prometheus-client
    - prompt-toolkit
    - psutil
    - py
    - pycodestyle
    - pycosat
    - pycparser
    - pycurl
    - pydocstyle
    - pyflakes
    - Pygments
    - PyGraph
    - pyinstaller
    - pyinstaller-hooks-contrib
    - pylint
    - pymzml
    - PyNaCl
    - pyodbc
    - PyOpenGL
    - pyOpenSSL
    - pyparsing
    - PyQt5
    - pyqt5-plugins
    - PyQt5-Qt
    - PyQt5-sip
    - pyqt5-tools
    - pyreadline
    - pyrsistent
    - pyserial
    - PySocks
    - pytest
    - python-dateutil
    - python-dotenv
    - python-jsonrpc-server
    - python-language-server
    - pytz
    - PyWavelets
    - pywin32
    - pywin32-ctypes
    - pywinpty
    - PyYAML
    - pyzmq
    - QDarkStyle
    - qt5-applications
    - qt5-tools
    - QtAwesome
    - qtconsole
    - QtPy
    - regex
    - requests
    - retrying
    - rope
    - Rtree
    - ruamel-yaml
    - scikit-image
    - scikit-learn
    - scipy
    - seaborn
    - Send2Trash
    - setuptools
    - simplegeneric
    - singledispatch
    - sip
    - six
    - snowballstemmer
    - sortedcollections
    - sortedcontainers
    - soupsieve
    - Sphinx
    - sphinxcontrib-applehelp
    - sphinxcontrib-devhelp
    - sphinxcontrib-htmlhelp
    - phinxcontrib-jsmath
    - sphinxcontrib-qthelp
    - sphinxcontrib-serializinghtml
    - sphinxcontrib-websupport
    - spyder
    - spyder-kernels
    - SQLAlchemy
    - statsmodels
    - sympy
    - tables
    - tblib
    - terminado
    - testpath
    - threadpoolctl
    - tifffile
    - toml
    - toolz
    - tornado
    - tqdm
    - traitlets
    - typing-extensions
    - ujson
    - unicodecsv
    - urllib3
    - vboxapi
    - watchdog
    - wcwidth
    - webencodings
    - Werkzeug
    - wheel
    - widgetsnbextension
    - win-inet-pton
    - win-unicode-console
    - wincertstore
    - wrapt
    - xlrd
    - XlsxWriter
    - xlwings
    - xlwt
    - xmltodict
    - yapf
    - zict
    - zipp
    - zope.event
    - zope.interface
